version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:${DB_PORT}/${DB_NAME}
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
